path_data = "../data/"
path_model = "./model/"

path_train_raw = path_data + "atec_nlp_sim_train_all.csv"
path_train_cut = path_data + "train_cut.csv"
path_train_string_distance = path_data + "train_string_dis.csv"
path_train_word2vec = path_data + "train_word2vec.csv"
path_train_string_diff = path_data + "train_string_diff.csv"
path_train_gram_feature = path_data + "train_gram_feature.csv"
path_train_doc2vec4 = path_data + "train_doc2vec4.csv"
path_train_features = path_data + "train_features.csv"

path_test = "../data/"
# path_test_raw = path_test + "atec_nlp_sim_test.csv"
# path_test_cut = path_test + "test_cut.csv"
# path_test_string_distance = path_test + "test_string_dis.csv"
# path_test_word2vec = path_test + "test_word2vec.csv"
# path_test_string_diff = path_test + "test_string_diff.csv"
# path_test_gram_feature = path_test + "test_gram_feature.csv"
# path_test_features = path_test + "test_features.csv"

path_test_raw = path_test + "atec_nlp_sim_test.csv"
path_test_cut = "test_cut.csv"
path_test_string_distance = "test_string_dis.csv"
path_test_word2vec = "test_word2vec.csv"
path_test_string_diff = "test_string_diff.csv"
path_test_gram_feature = "test_gram_feature.csv"
path_test_doc2vec4 = "test_doc2vec4.csv"
path_test_features = "test_features.csv"
